baseURL = "https://archivedchaos.com/"
languageCode = "en-us"
title = "Archived Chaos"
paginate = 10

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]
  dateFormat = "January 2, 2006 - 3:04PM MST"

[taxonomies]
  tag = "tags"
