baseURL = "/"
languageCode = "en-us"
title = "Archived Chaos"
paginate = 10
disableKinds = [ "section" ]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    name = "Archive"
    url = "/archive/"

[params]
  dateFormat = "January 2, 2006 - 3:04PM MST"
  brand = "Archived Chaos"

[taxonomies]
  tag = "tags"
